# Generated by Django 3.1.6 on 2021-05-24 15:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='template',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/yannlegros/Documents/helios/Centralized-Platform/backend/actions/ansible'), upload_to=''),
        ),
    ]
