# Generated by Django 3.1.6 on 2021-05-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_scheduledtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='time',
            field=models.CharField(max_length=11),
        ),
    ]
