# Generated by Django 3.1.6 on 2021-05-25 08:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20210524_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='template',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\legro\\Documents\\ETSETB\\4B\\TFG\\Centralized-Platform\\backend\\actions\\ansible'), upload_to=''),
        ),
    ]
