---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    dst: "8.8.8.8"
  tasks:
    - name: ping
      shell: ping -c 1 -w 2 {{ dst }}
      register: result
      failed_when: "'100% packet loss' in result.stdout"
    - debug: msg={{result.stdout_lines[4]}}