# Generated by Django 3.1.6 on 2021-04-12 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=100, null=True, unique=True)),
                ('mode', models.CharField(choices=[('active', 'Active'), ('down', 'Down')], default='down', max_length=30)),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('unstable', 'Unstable'), ('critical', 'Critical')], default='stable', max_length=30)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('operating_system', models.CharField(max_length=30, null=True)),
                ('sw_version', models.CharField(max_length=30, null=True)),
                ('hw_end_of_life', models.DateTimeField(null=True)),
                ('sw_end_of_life', models.DateTimeField(null=True)),
                ('zone', models.CharField(max_length=30, null=True)),
                ('area', models.CharField(max_length=30, null=True)),
                ('group', models.CharField(max_length=50, null=True)),
                ('fqdn', models.CharField(max_length=300, null=True)),
                ('contact_person', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogicPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DevicesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='inventory.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='logic_partition',
            field=models.ManyToManyField(blank=True, to='inventory.LogicPartition'),
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_code', models.CharField(max_length=13, unique=True)),
                ('old_info', models.JSONField()),
                ('new_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('documentation', models.FileField(null=True, upload_to='changes/%Y/%m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
