# Generated by Django 3.1.6 on 2021-02-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mh', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('ip_address', models.CharField(max_length=30, null=True, verbose_name='IP Address')),
                ('device_type', models.CharField(max_length=100, null=True, verbose_name='Device Type')),
                ('security_string', models.CharField(max_length=100, null=True, verbose_name='Security String')),
                ('system_uptime', models.BigIntegerField(null=True, verbose_name='System Uptime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_systemuptime', models.BooleanField(default=False)),
            ],
        ),
    ]
