# Generated by Django 3.1.6 on 2021-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='new_info',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='old_info',
            field=models.JSONField(null=True),
        ),
    ]
