# Generated by Django 3.1.6 on 2021-03-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='celery_systemuptime',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mh',
        ),
        migrations.RemoveField(
            model_name='device',
            name='security_string',
        ),
        migrations.RemoveField(
            model_name='device',
            name='system_uptime',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
    ]
