# Generated by Django 3.1.6 on 2021-04-30 19:52

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_auto_20210412_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevicesComment',
            new_name='DeviceComment',
        ),
        migrations.RemoveField(
            model_name='change',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='change',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='change',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='change',
            name='user',
        ),
        migrations.AlterField(
            model_name='change',
            name='change_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='new_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='change',
            name='old_info',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='FutureChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_code', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_urgent', models.BooleanField(blank=True, default=False, null=True)),
                ('rfc', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\legro\\Documents\\ETSETB\\4B\\TFG\\Centralized-Platform\\backend\\inventory\\files\\changes'), upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
