# Generated by Django 3.1.6 on 2021-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210307_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='IP Address'),
        ),
    ]
