# Generated by Django 3.1.6 on 2021-04-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210307_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='area',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='create_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='fqdn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hw_end_of_life',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sw_end_of_life',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sw_version',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_device_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DevicesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('comment', models.TextField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='inventory.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='logic_partition',
            field=models.ManyToManyField(to='inventory.LogicPartition'),
        ),
    ]
