# Generated by Django 3.1.6 on 2021-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210430_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurechange',
            name='type',
            field=models.CharField(blank=True, choices=[('corrective', 'Corrective'), ('evolutionary', 'Evolutionary'), ('pre-approved', 'Pre-approved')], max_length=50, null=True),
        ),
    ]
