# Generated by Django 3.1.6 on 2021-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210430_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurechange',
            old_name='user',
            new_name='executor',
        ),
        migrations.AddField(
            model_name='futurechange',
            name='requestor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
