# Generated by Django 3.1.6 on 2021-04-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210402_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicpartition',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
