# Generated by Django 3.1.6 on 2021-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210403_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='logic_partition',
            field=models.ManyToManyField(blank=True, to='inventory.LogicPartition'),
        ),
        migrations.AlterField(
            model_name='logicpartition',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
