# Generated by Django 3.1.6 on 2021-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210403_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('active', 'Active'), ('down', 'Down')], default='down', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('stable', 'Stable'), ('unstable', 'Unstable'), ('critical', 'Critical')], default='stable', max_length=30),
        ),
    ]
