# Generated by Django 3.1.6 on 2021-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210511_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
