# Generated by Django 3.1.6 on 2021-05-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
