# Generated by Django 3.1.6 on 2021-05-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210514_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='date',
        ),
    ]
