# Generated by Django 3.1.6 on 2021-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210515_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('not_connected', 'Not connected'), ('disabled', 'Disabled')], max_length=100, null=True),
        ),
    ]
