# Generated by Django 3.1.6 on 2021-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210515_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_address', models.GenericIPAddressField()),
                ('netmask', models.IntegerField()),
                ('zone', models.CharField(blank=True, max_length=150, null=True)),
                ('vlan', models.CharField(blank=True, max_length=100, null=True)),
                ('vrf', models.CharField(blank=True, max_length=100, null=True)),
                ('firewall', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
