# Generated by Django 3.1.6 on 2021-05-24 15:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurechange',
            name='rfc',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/yannlegros/Documents/helios/Centralized-Platform/backend/inventory/files/changes'), upload_to=''),
        ),
    ]
