# Generated by Django 3.1.6 on 2021-05-25 08:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210524_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurechange',
            name='rfc',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\legro\\Documents\\ETSETB\\4B\\TFG\\Centralized-Platform\\backend\\inventory\\files\\changes'), upload_to=''),
        ),
    ]
